/*
Facturapi

<br /> <br />  En esta página enlistamos todos los métodos disponibles en la API de Facturapi, así como la referencia completa de los parámetros que acepta cada uno. Para ver las propiedades anidadas de un objeto o arreglo de objetos, puedes hacer clic sobre el nombre del campo y expandirlo.  La API de Facturapi está diseñada con el estándar [REST](https://developer.mozilla.org/en-US/docs/Glossary/REST) en mente. Los endpoints de la API están agrupados por recursos, tienen URLs predecibles, las respuestas tienen formato JSON y usamos códigos HTTP de respuesta, autenticación y verbos estándar.  Durante el desarrollo, puedes usar la API de Facturapi en ambiente Test y las facturas que emitas no se enviarán al SAT ni tendrán validez fiscal.  La llave secreta que utilices para autenticarte determinará tanto el ambiente en el que se creará la factura (Test o Live), así como la organización a utilizar como emisor de tu factura, o bien como dueña del recurso que solicites crear. 

API version: 2.0
Contact: soporte@facturapi.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the NominaComplementDataNestedInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NominaComplementDataNestedInput{}

// NominaComplementDataNestedInput struct for NominaComplementDataNestedInput
type NominaComplementDataNestedInput struct {
	Emisor *NominaEmisorProperties `json:"emisor,omitempty"`
	Receptor *NominaReceptorInput `json:"receptor,omitempty"`
	Percepciones *NominaPercepcionesInput `json:"percepciones,omitempty"`
	Deducciones []NominaDeduccionInput `json:"deducciones,omitempty"`
	OtrosPagos []OtroPago `json:"otros_pagos,omitempty"`
	Incapacidades []NominaIncapacidadInput `json:"incapacidades,omitempty"`
}

// NewNominaComplementDataNestedInput instantiates a new NominaComplementDataNestedInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNominaComplementDataNestedInput() *NominaComplementDataNestedInput {
	this := NominaComplementDataNestedInput{}
	return &this
}

// NewNominaComplementDataNestedInputWithDefaults instantiates a new NominaComplementDataNestedInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNominaComplementDataNestedInputWithDefaults() *NominaComplementDataNestedInput {
	this := NominaComplementDataNestedInput{}
	return &this
}

// GetEmisor returns the Emisor field value if set, zero value otherwise.
func (o *NominaComplementDataNestedInput) GetEmisor() NominaEmisorProperties {
	if o == nil || IsNil(o.Emisor) {
		var ret NominaEmisorProperties
		return ret
	}
	return *o.Emisor
}

// GetEmisorOk returns a tuple with the Emisor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NominaComplementDataNestedInput) GetEmisorOk() (*NominaEmisorProperties, bool) {
	if o == nil || IsNil(o.Emisor) {
		return nil, false
	}
	return o.Emisor, true
}

// HasEmisor returns a boolean if a field has been set.
func (o *NominaComplementDataNestedInput) HasEmisor() bool {
	if o != nil && !IsNil(o.Emisor) {
		return true
	}

	return false
}

// SetEmisor gets a reference to the given NominaEmisorProperties and assigns it to the Emisor field.
func (o *NominaComplementDataNestedInput) SetEmisor(v NominaEmisorProperties) {
	o.Emisor = &v
}

// GetReceptor returns the Receptor field value if set, zero value otherwise.
func (o *NominaComplementDataNestedInput) GetReceptor() NominaReceptorInput {
	if o == nil || IsNil(o.Receptor) {
		var ret NominaReceptorInput
		return ret
	}
	return *o.Receptor
}

// GetReceptorOk returns a tuple with the Receptor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NominaComplementDataNestedInput) GetReceptorOk() (*NominaReceptorInput, bool) {
	if o == nil || IsNil(o.Receptor) {
		return nil, false
	}
	return o.Receptor, true
}

// HasReceptor returns a boolean if a field has been set.
func (o *NominaComplementDataNestedInput) HasReceptor() bool {
	if o != nil && !IsNil(o.Receptor) {
		return true
	}

	return false
}

// SetReceptor gets a reference to the given NominaReceptorInput and assigns it to the Receptor field.
func (o *NominaComplementDataNestedInput) SetReceptor(v NominaReceptorInput) {
	o.Receptor = &v
}

// GetPercepciones returns the Percepciones field value if set, zero value otherwise.
func (o *NominaComplementDataNestedInput) GetPercepciones() NominaPercepcionesInput {
	if o == nil || IsNil(o.Percepciones) {
		var ret NominaPercepcionesInput
		return ret
	}
	return *o.Percepciones
}

// GetPercepcionesOk returns a tuple with the Percepciones field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NominaComplementDataNestedInput) GetPercepcionesOk() (*NominaPercepcionesInput, bool) {
	if o == nil || IsNil(o.Percepciones) {
		return nil, false
	}
	return o.Percepciones, true
}

// HasPercepciones returns a boolean if a field has been set.
func (o *NominaComplementDataNestedInput) HasPercepciones() bool {
	if o != nil && !IsNil(o.Percepciones) {
		return true
	}

	return false
}

// SetPercepciones gets a reference to the given NominaPercepcionesInput and assigns it to the Percepciones field.
func (o *NominaComplementDataNestedInput) SetPercepciones(v NominaPercepcionesInput) {
	o.Percepciones = &v
}

// GetDeducciones returns the Deducciones field value if set, zero value otherwise.
func (o *NominaComplementDataNestedInput) GetDeducciones() []NominaDeduccionInput {
	if o == nil || IsNil(o.Deducciones) {
		var ret []NominaDeduccionInput
		return ret
	}
	return o.Deducciones
}

// GetDeduccionesOk returns a tuple with the Deducciones field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NominaComplementDataNestedInput) GetDeduccionesOk() ([]NominaDeduccionInput, bool) {
	if o == nil || IsNil(o.Deducciones) {
		return nil, false
	}
	return o.Deducciones, true
}

// HasDeducciones returns a boolean if a field has been set.
func (o *NominaComplementDataNestedInput) HasDeducciones() bool {
	if o != nil && !IsNil(o.Deducciones) {
		return true
	}

	return false
}

// SetDeducciones gets a reference to the given []NominaDeduccionInput and assigns it to the Deducciones field.
func (o *NominaComplementDataNestedInput) SetDeducciones(v []NominaDeduccionInput) {
	o.Deducciones = v
}

// GetOtrosPagos returns the OtrosPagos field value if set, zero value otherwise.
func (o *NominaComplementDataNestedInput) GetOtrosPagos() []OtroPago {
	if o == nil || IsNil(o.OtrosPagos) {
		var ret []OtroPago
		return ret
	}
	return o.OtrosPagos
}

// GetOtrosPagosOk returns a tuple with the OtrosPagos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NominaComplementDataNestedInput) GetOtrosPagosOk() ([]OtroPago, bool) {
	if o == nil || IsNil(o.OtrosPagos) {
		return nil, false
	}
	return o.OtrosPagos, true
}

// HasOtrosPagos returns a boolean if a field has been set.
func (o *NominaComplementDataNestedInput) HasOtrosPagos() bool {
	if o != nil && !IsNil(o.OtrosPagos) {
		return true
	}

	return false
}

// SetOtrosPagos gets a reference to the given []OtroPago and assigns it to the OtrosPagos field.
func (o *NominaComplementDataNestedInput) SetOtrosPagos(v []OtroPago) {
	o.OtrosPagos = v
}

// GetIncapacidades returns the Incapacidades field value if set, zero value otherwise.
func (o *NominaComplementDataNestedInput) GetIncapacidades() []NominaIncapacidadInput {
	if o == nil || IsNil(o.Incapacidades) {
		var ret []NominaIncapacidadInput
		return ret
	}
	return o.Incapacidades
}

// GetIncapacidadesOk returns a tuple with the Incapacidades field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NominaComplementDataNestedInput) GetIncapacidadesOk() ([]NominaIncapacidadInput, bool) {
	if o == nil || IsNil(o.Incapacidades) {
		return nil, false
	}
	return o.Incapacidades, true
}

// HasIncapacidades returns a boolean if a field has been set.
func (o *NominaComplementDataNestedInput) HasIncapacidades() bool {
	if o != nil && !IsNil(o.Incapacidades) {
		return true
	}

	return false
}

// SetIncapacidades gets a reference to the given []NominaIncapacidadInput and assigns it to the Incapacidades field.
func (o *NominaComplementDataNestedInput) SetIncapacidades(v []NominaIncapacidadInput) {
	o.Incapacidades = v
}

func (o NominaComplementDataNestedInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NominaComplementDataNestedInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Emisor) {
		toSerialize["emisor"] = o.Emisor
	}
	if !IsNil(o.Receptor) {
		toSerialize["receptor"] = o.Receptor
	}
	if !IsNil(o.Percepciones) {
		toSerialize["percepciones"] = o.Percepciones
	}
	if !IsNil(o.Deducciones) {
		toSerialize["deducciones"] = o.Deducciones
	}
	if !IsNil(o.OtrosPagos) {
		toSerialize["otros_pagos"] = o.OtrosPagos
	}
	if !IsNil(o.Incapacidades) {
		toSerialize["incapacidades"] = o.Incapacidades
	}
	return toSerialize, nil
}

type NullableNominaComplementDataNestedInput struct {
	value *NominaComplementDataNestedInput
	isSet bool
}

func (v NullableNominaComplementDataNestedInput) Get() *NominaComplementDataNestedInput {
	return v.value
}

func (v *NullableNominaComplementDataNestedInput) Set(val *NominaComplementDataNestedInput) {
	v.value = val
	v.isSet = true
}

func (v NullableNominaComplementDataNestedInput) IsSet() bool {
	return v.isSet
}

func (v *NullableNominaComplementDataNestedInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNominaComplementDataNestedInput(val *NominaComplementDataNestedInput) *NullableNominaComplementDataNestedInput {
	return &NullableNominaComplementDataNestedInput{value: val, isSet: true}
}

func (v NullableNominaComplementDataNestedInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNominaComplementDataNestedInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


