/*
Facturapi

<br /> <br />  En esta página enlistamos todos los métodos disponibles en la API de Facturapi, así como la referencia completa de los parámetros que acepta cada uno. Para ver las propiedades anidadas de un objeto o arreglo de objetos, puedes hacer clic sobre el nombre del campo y expandirlo.  La API de Facturapi está diseñada con el estándar [REST](https://developer.mozilla.org/en-US/docs/Glossary/REST) en mente. Los endpoints de la API están agrupados por recursos, tienen URLs predecibles, las respuestas tienen formato JSON y usamos códigos HTTP de respuesta, autenticación y verbos estándar.  Durante el desarrollo, puedes usar la API de Facturapi en ambiente Test y las facturas que emitas no se enviarán al SAT ni tendrán validez fiscal.  La llave secreta que utilices para autenticarte determinará tanto el ambiente en el que se creará la factura (Test o Live), así como la organización a utilizar como emisor de tu factura, o bien como dueña del recurso que solicites crear. 

API version: 2.0
Contact: soporte@facturapi.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the NominaComplementDataDirectProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NominaComplementDataDirectProperties{}

// NominaComplementDataDirectProperties struct for NominaComplementDataDirectProperties
type NominaComplementDataDirectProperties struct {
	// Tipo de nómina. - `“O”` (Ordinaria): Cuando corresponde a un pago que se realiza de manera habitual, como sueldos. - `“E”` (Extraordinaria): Para pagos fuera de lo habitual, como liquidaciones, aguinaldos o bonos. 
	TipoNomina *string `json:"tipo_nomina,omitempty"`
	// Fecha de pago de la nómina al trabajador.
	FechaPago *string `json:"fecha_pago,omitempty"`
	// Fecha inicial del periodo de pago.
	FechaInicialPago *string `json:"fecha_inicial_pago,omitempty"`
	// Fecha final del periodo de pago.
	FechaFinalPago *string `json:"fecha_final_pago,omitempty"`
	// Número de días pagados. Puede ser entero o fracción.
	NumDiasPagados *float32 `json:"num_dias_pagados,omitempty"`
}

// NewNominaComplementDataDirectProperties instantiates a new NominaComplementDataDirectProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNominaComplementDataDirectProperties() *NominaComplementDataDirectProperties {
	this := NominaComplementDataDirectProperties{}
	var tipoNomina string = "O"
	this.TipoNomina = &tipoNomina
	var fechaPago string = "now"
	this.FechaPago = &fechaPago
	return &this
}

// NewNominaComplementDataDirectPropertiesWithDefaults instantiates a new NominaComplementDataDirectProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNominaComplementDataDirectPropertiesWithDefaults() *NominaComplementDataDirectProperties {
	this := NominaComplementDataDirectProperties{}
	var tipoNomina string = "O"
	this.TipoNomina = &tipoNomina
	var fechaPago string = "now"
	this.FechaPago = &fechaPago
	return &this
}

// GetTipoNomina returns the TipoNomina field value if set, zero value otherwise.
func (o *NominaComplementDataDirectProperties) GetTipoNomina() string {
	if o == nil || IsNil(o.TipoNomina) {
		var ret string
		return ret
	}
	return *o.TipoNomina
}

// GetTipoNominaOk returns a tuple with the TipoNomina field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NominaComplementDataDirectProperties) GetTipoNominaOk() (*string, bool) {
	if o == nil || IsNil(o.TipoNomina) {
		return nil, false
	}
	return o.TipoNomina, true
}

// HasTipoNomina returns a boolean if a field has been set.
func (o *NominaComplementDataDirectProperties) HasTipoNomina() bool {
	if o != nil && !IsNil(o.TipoNomina) {
		return true
	}

	return false
}

// SetTipoNomina gets a reference to the given string and assigns it to the TipoNomina field.
func (o *NominaComplementDataDirectProperties) SetTipoNomina(v string) {
	o.TipoNomina = &v
}

// GetFechaPago returns the FechaPago field value if set, zero value otherwise.
func (o *NominaComplementDataDirectProperties) GetFechaPago() string {
	if o == nil || IsNil(o.FechaPago) {
		var ret string
		return ret
	}
	return *o.FechaPago
}

// GetFechaPagoOk returns a tuple with the FechaPago field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NominaComplementDataDirectProperties) GetFechaPagoOk() (*string, bool) {
	if o == nil || IsNil(o.FechaPago) {
		return nil, false
	}
	return o.FechaPago, true
}

// HasFechaPago returns a boolean if a field has been set.
func (o *NominaComplementDataDirectProperties) HasFechaPago() bool {
	if o != nil && !IsNil(o.FechaPago) {
		return true
	}

	return false
}

// SetFechaPago gets a reference to the given string and assigns it to the FechaPago field.
func (o *NominaComplementDataDirectProperties) SetFechaPago(v string) {
	o.FechaPago = &v
}

// GetFechaInicialPago returns the FechaInicialPago field value if set, zero value otherwise.
func (o *NominaComplementDataDirectProperties) GetFechaInicialPago() string {
	if o == nil || IsNil(o.FechaInicialPago) {
		var ret string
		return ret
	}
	return *o.FechaInicialPago
}

// GetFechaInicialPagoOk returns a tuple with the FechaInicialPago field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NominaComplementDataDirectProperties) GetFechaInicialPagoOk() (*string, bool) {
	if o == nil || IsNil(o.FechaInicialPago) {
		return nil, false
	}
	return o.FechaInicialPago, true
}

// HasFechaInicialPago returns a boolean if a field has been set.
func (o *NominaComplementDataDirectProperties) HasFechaInicialPago() bool {
	if o != nil && !IsNil(o.FechaInicialPago) {
		return true
	}

	return false
}

// SetFechaInicialPago gets a reference to the given string and assigns it to the FechaInicialPago field.
func (o *NominaComplementDataDirectProperties) SetFechaInicialPago(v string) {
	o.FechaInicialPago = &v
}

// GetFechaFinalPago returns the FechaFinalPago field value if set, zero value otherwise.
func (o *NominaComplementDataDirectProperties) GetFechaFinalPago() string {
	if o == nil || IsNil(o.FechaFinalPago) {
		var ret string
		return ret
	}
	return *o.FechaFinalPago
}

// GetFechaFinalPagoOk returns a tuple with the FechaFinalPago field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NominaComplementDataDirectProperties) GetFechaFinalPagoOk() (*string, bool) {
	if o == nil || IsNil(o.FechaFinalPago) {
		return nil, false
	}
	return o.FechaFinalPago, true
}

// HasFechaFinalPago returns a boolean if a field has been set.
func (o *NominaComplementDataDirectProperties) HasFechaFinalPago() bool {
	if o != nil && !IsNil(o.FechaFinalPago) {
		return true
	}

	return false
}

// SetFechaFinalPago gets a reference to the given string and assigns it to the FechaFinalPago field.
func (o *NominaComplementDataDirectProperties) SetFechaFinalPago(v string) {
	o.FechaFinalPago = &v
}

// GetNumDiasPagados returns the NumDiasPagados field value if set, zero value otherwise.
func (o *NominaComplementDataDirectProperties) GetNumDiasPagados() float32 {
	if o == nil || IsNil(o.NumDiasPagados) {
		var ret float32
		return ret
	}
	return *o.NumDiasPagados
}

// GetNumDiasPagadosOk returns a tuple with the NumDiasPagados field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NominaComplementDataDirectProperties) GetNumDiasPagadosOk() (*float32, bool) {
	if o == nil || IsNil(o.NumDiasPagados) {
		return nil, false
	}
	return o.NumDiasPagados, true
}

// HasNumDiasPagados returns a boolean if a field has been set.
func (o *NominaComplementDataDirectProperties) HasNumDiasPagados() bool {
	if o != nil && !IsNil(o.NumDiasPagados) {
		return true
	}

	return false
}

// SetNumDiasPagados gets a reference to the given float32 and assigns it to the NumDiasPagados field.
func (o *NominaComplementDataDirectProperties) SetNumDiasPagados(v float32) {
	o.NumDiasPagados = &v
}

func (o NominaComplementDataDirectProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NominaComplementDataDirectProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TipoNomina) {
		toSerialize["tipo_nomina"] = o.TipoNomina
	}
	if !IsNil(o.FechaPago) {
		toSerialize["fecha_pago"] = o.FechaPago
	}
	if !IsNil(o.FechaInicialPago) {
		toSerialize["fecha_inicial_pago"] = o.FechaInicialPago
	}
	if !IsNil(o.FechaFinalPago) {
		toSerialize["fecha_final_pago"] = o.FechaFinalPago
	}
	if !IsNil(o.NumDiasPagados) {
		toSerialize["num_dias_pagados"] = o.NumDiasPagados
	}
	return toSerialize, nil
}

type NullableNominaComplementDataDirectProperties struct {
	value *NominaComplementDataDirectProperties
	isSet bool
}

func (v NullableNominaComplementDataDirectProperties) Get() *NominaComplementDataDirectProperties {
	return v.value
}

func (v *NullableNominaComplementDataDirectProperties) Set(val *NominaComplementDataDirectProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableNominaComplementDataDirectProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableNominaComplementDataDirectProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNominaComplementDataDirectProperties(val *NominaComplementDataDirectProperties) *NullableNominaComplementDataDirectProperties {
	return &NullableNominaComplementDataDirectProperties{value: val, isSet: true}
}

func (v NullableNominaComplementDataDirectProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNominaComplementDataDirectProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


