/*
Facturapi

<br /> <br />  En esta página enlistamos todos los métodos disponibles en la API de Facturapi, así como la referencia completa de los parámetros que acepta cada uno. Para ver las propiedades anidadas de un objeto o arreglo de objetos, puedes hacer clic sobre el nombre del campo y expandirlo.  La API de Facturapi está diseñada con el estándar [REST](https://developer.mozilla.org/en-US/docs/Glossary/REST) en mente. Los endpoints de la API están agrupados por recursos, tienen URLs predecibles, las respuestas tienen formato JSON y usamos códigos HTTP de respuesta, autenticación y verbos estándar.  Durante el desarrollo, puedes usar la API de Facturapi en ambiente Test y las facturas que emitas no se enviarán al SAT ni tendrán validez fiscal.  La llave secreta que utilices para autenticarte determinará tanto el ambiente en el que se creará la factura (Test o Live), así como la organización a utilizar como emisor de tu factura, o bien como dueña del recurso que solicites crear. 

API version: 2.0
Contact: soporte@facturapi.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package facturapi-go

import (
	"encoding/json"
)

// checks if the NominaAccionesInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NominaAccionesInput{}

// NominaAccionesInput struct for NominaAccionesInput
type NominaAccionesInput struct {
	// Valor de mercado de las Acciones o Títulos valor al ejercer la opción.
	ValorMercado float32 `json:"valor_mercado"`
	// Precio establecido al otorgarse la opción de ingresos en acciones o títulos valor.
	PrecioAlOtorgarse float32 `json:"precio_al_otorgarse"`
}

// NewNominaAccionesInput instantiates a new NominaAccionesInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNominaAccionesInput(valorMercado float32, precioAlOtorgarse float32) *NominaAccionesInput {
	this := NominaAccionesInput{}
	this.ValorMercado = valorMercado
	this.PrecioAlOtorgarse = precioAlOtorgarse
	return &this
}

// NewNominaAccionesInputWithDefaults instantiates a new NominaAccionesInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNominaAccionesInputWithDefaults() *NominaAccionesInput {
	this := NominaAccionesInput{}
	return &this
}

// GetValorMercado returns the ValorMercado field value
func (o *NominaAccionesInput) GetValorMercado() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ValorMercado
}

// GetValorMercadoOk returns a tuple with the ValorMercado field value
// and a boolean to check if the value has been set.
func (o *NominaAccionesInput) GetValorMercadoOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValorMercado, true
}

// SetValorMercado sets field value
func (o *NominaAccionesInput) SetValorMercado(v float32) {
	o.ValorMercado = v
}

// GetPrecioAlOtorgarse returns the PrecioAlOtorgarse field value
func (o *NominaAccionesInput) GetPrecioAlOtorgarse() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PrecioAlOtorgarse
}

// GetPrecioAlOtorgarseOk returns a tuple with the PrecioAlOtorgarse field value
// and a boolean to check if the value has been set.
func (o *NominaAccionesInput) GetPrecioAlOtorgarseOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrecioAlOtorgarse, true
}

// SetPrecioAlOtorgarse sets field value
func (o *NominaAccionesInput) SetPrecioAlOtorgarse(v float32) {
	o.PrecioAlOtorgarse = v
}

func (o NominaAccionesInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NominaAccionesInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["valor_mercado"] = o.ValorMercado
	toSerialize["precio_al_otorgarse"] = o.PrecioAlOtorgarse
	return toSerialize, nil
}

type NullableNominaAccionesInput struct {
	value *NominaAccionesInput
	isSet bool
}

func (v NullableNominaAccionesInput) Get() *NominaAccionesInput {
	return v.value
}

func (v *NullableNominaAccionesInput) Set(val *NominaAccionesInput) {
	v.value = val
	v.isSet = true
}

func (v NullableNominaAccionesInput) IsSet() bool {
	return v.isSet
}

func (v *NullableNominaAccionesInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNominaAccionesInput(val *NominaAccionesInput) *NullableNominaAccionesInput {
	return &NullableNominaAccionesInput{value: val, isSet: true}
}

func (v NullableNominaAccionesInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNominaAccionesInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


