/*
Facturapi

<br /> <br />  En esta página enlistamos todos los métodos disponibles en la API de Facturapi, así como la referencia completa de los parámetros que acepta cada uno. Para ver las propiedades anidadas de un objeto o arreglo de objetos, puedes hacer clic sobre el nombre del campo y expandirlo.  La API de Facturapi está diseñada con el estándar [REST](https://developer.mozilla.org/en-US/docs/Glossary/REST) en mente. Los endpoints de la API están agrupados por recursos, tienen URLs predecibles, las respuestas tienen formato JSON y usamos códigos HTTP de respuesta, autenticación y verbos estándar.  Durante el desarrollo, puedes usar la API de Facturapi en ambiente Test y las facturas que emitas no se enviarán al SAT ni tendrán validez fiscal.  La llave secreta que utilices para autenticarte determinará tanto el ambiente en el que se creará la factura (Test o Live), así como la organización a utilizar como emisor de tu factura, o bien como dueña del recurso que solicites crear. 

API version: 2.0
Contact: soporte@facturapi.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package facturapi-go

import (
	"encoding/json"
)

// checks if the NominaComplementProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NominaComplementProperties{}

// NominaComplementProperties struct for NominaComplementProperties
type NominaComplementProperties struct {
	NominaOrCustomComplementProperties
	Data *NominaComplementDataProperties `json:"data,omitempty"`
}

// NewNominaComplementProperties instantiates a new NominaComplementProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNominaComplementProperties() *NominaComplementProperties {
	this := NominaComplementProperties{}
	return &this
}

// NewNominaComplementPropertiesWithDefaults instantiates a new NominaComplementProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNominaComplementPropertiesWithDefaults() *NominaComplementProperties {
	this := NominaComplementProperties{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *NominaComplementProperties) GetData() NominaComplementDataProperties {
	if o == nil || IsNil(o.Data) {
		var ret NominaComplementDataProperties
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NominaComplementProperties) GetDataOk() (*NominaComplementDataProperties, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *NominaComplementProperties) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given NominaComplementDataProperties and assigns it to the Data field.
func (o *NominaComplementProperties) SetData(v NominaComplementDataProperties) {
	o.Data = &v
}

func (o NominaComplementProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NominaComplementProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedNominaOrCustomComplementProperties, errNominaOrCustomComplementProperties := json.Marshal(o.NominaOrCustomComplementProperties)
	if errNominaOrCustomComplementProperties != nil {
		return map[string]interface{}{}, errNominaOrCustomComplementProperties
	}
	errNominaOrCustomComplementProperties = json.Unmarshal([]byte(serializedNominaOrCustomComplementProperties), &toSerialize)
	if errNominaOrCustomComplementProperties != nil {
		return map[string]interface{}{}, errNominaOrCustomComplementProperties
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableNominaComplementProperties struct {
	value *NominaComplementProperties
	isSet bool
}

func (v NullableNominaComplementProperties) Get() *NominaComplementProperties {
	return v.value
}

func (v *NullableNominaComplementProperties) Set(val *NominaComplementProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableNominaComplementProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableNominaComplementProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNominaComplementProperties(val *NominaComplementProperties) *NullableNominaComplementProperties {
	return &NullableNominaComplementProperties{value: val, isSet: true}
}

func (v NullableNominaComplementProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNominaComplementProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


